create table if not exists public.leaderboard_scores (
    id bigint generated by default as identity primary key,
    player_name text not null check (
        char_length(btrim(player_name)) between 1 and 12
        and player_name = btrim(player_name)
        and player_name !~ '[[:cntrl:]]'
    ),
    score integer not null check (score > 0 and score <= 6000),
    created_at timestamptz not null default now()
);

alter table public.leaderboard_scores
drop constraint if exists leaderboard_scores_score_check;

alter table public.leaderboard_scores
add constraint leaderboard_scores_score_check
check (score > 0 and score <= 6000);

alter table public.leaderboard_scores
drop constraint if exists leaderboard_scores_player_name_check;

alter table public.leaderboard_scores
add constraint leaderboard_scores_player_name_check
check (
    char_length(btrim(player_name)) between 1 and 12
    and player_name = btrim(player_name)
    and player_name !~ '[[:cntrl:]]'
);

create index if not exists leaderboard_scores_score_created_idx
on public.leaderboard_scores (score desc, created_at asc);

alter table public.leaderboard_scores enable row level security;

drop policy if exists "leaderboard_scores_select_all" on public.leaderboard_scores;
create policy "leaderboard_scores_select_all"
on public.leaderboard_scores
for select
to anon, authenticated
using (true);

drop policy if exists "leaderboard_scores_insert_all" on public.leaderboard_scores;
-- Writes now go through the submit-score Edge Function using the service role key.
-- Keep direct inserts closed for anon/authenticated browser clients.

create table if not exists public.site_visits (
    visit_date date not null,
    visitor_id uuid not null,
    created_at timestamptz not null default now(),
    primary key (visit_date, visitor_id)
);

create index if not exists site_visits_created_at_idx
on public.site_visits (created_at desc);

alter table public.site_visits enable row level security;

drop policy if exists "site_visits_select_all" on public.site_visits;
create policy "site_visits_select_all"
on public.site_visits
for select
to anon, authenticated
using (true);

drop policy if exists "site_visits_insert_all" on public.site_visits;
create policy "site_visits_insert_all"
on public.site_visits
for insert
to anon, authenticated
with check (true);
