create table if not exists public.leaderboard_scores (
    id bigint generated by default as identity primary key,
    player_name text not null check (char_length(player_name) between 1 and 12),
    score integer not null check (score > 0),
    created_at timestamptz not null default now()
);

alter table public.leaderboard_scores enable row level security;

drop policy if exists "leaderboard_scores_select_all" on public.leaderboard_scores;
create policy "leaderboard_scores_select_all"
on public.leaderboard_scores
for select
to anon, authenticated
using (true);

drop policy if exists "leaderboard_scores_insert_all" on public.leaderboard_scores;
create policy "leaderboard_scores_insert_all"
on public.leaderboard_scores
for insert
to anon, authenticated
with check (true);
